language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/javascriptcafe_test
node_js:  
  - "8.1.0"
before_script:
  - psql -c 'create database javascriptcafe_test;' -U postgres
  - psql -U postgres -d javascriptcafe_test -a -f tables.sql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5